version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./server
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"
    depends_on:
      - mongo

volumes:
  mongo_data:
